### ISSUE TITLE
Issue with Kakaobank post URL

### ISSUE THREAD

**Issue by divingbeetle** [hugehoo/blog-gopher#1]
2024년 6월 이전 카카오뱅크 블로그 포스트의 URL이 정상 작동하지 않습니다.
웹사이트 링크를 확인해보니 `https://tech.kakaobank.com../../posts/2405-predicting-cryptocurrency-prices-with-chatgpt/` 이런 식으로 걸려 있어서 생긴 문제였습니다.

카카오뱅크에서 포스트 URL이 상대 링크로 걸려 있는 것이 원인으로 보입니다.

카카오뱅크 기술 블로그 html을 확인 해본 결과

1페이지, `https://tech.kakaobank.com/` 의 포스트는
```html
<a href="./posts/2408-msbuild-2024/">두 엔지니어의 시선으로 본 Microsoft Build 2024</a>
```
2페이지 이후, `https://tech.kakaobank.com/page/2/` 부터는
```html
<a href="../../posts/2405-how_to_integrate_terraform_in_kakaobank/">테라폼의 풍미를 더해주는 서버 설정 자동화 한 스푼 🥣</a>
```
이렇게 링크가 적혀 있습니다.

`KakaobankScrapper.go` 에서 포스트 url을 가져올 때 아예 포스트 제목만 가져오거나,
`net/url` 패키지의 `ResolveReference` 함수를 사용하는 것으로 해결 할 수 있을 것으로 보입니다.

**Comment by divingbeetle** [comment]
혹은 https://tech.kakaobank.com/index.xml 를 사용해도 좋을 것 같습니다.

**Comment by hugehoo** [comment]
@divingbeetle 안녕하세요 해당 이슈 수정됐습니다! 제보 주셔서 감사합니다.
+ 혹시 카뱅 블로그에 rss 링크는 어떻게 아셨는지 알 수 있을까요?.?

**Comment by divingbeetle** [comment]
> @divingbeetle 안녕하세요 해당 이슈 수정됐습니다! 제보 주셔서 감사합니다.
> + 혹시 카뱅 블로그에 rss 링크는 어떻게 아셨는지 알 수 있을까요?.?

그냥 html에다 대고 rss 검색해봤어요 ㅎㅋㄲ
